# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
     
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        shell: bash
        run: |
          sudo apt update
          sudo apt install make
          
      - name: install go
        uses: actions/setup-go@v2.1.3
        with:
             go-version: 1.15
      
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: test controller
        shell: bash
        run: |
          make test
 
      - name: docker-build
        uses: docker/setup-buildx-action@v1.0.3
