# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
     
  # This workflow contains a single job called "build"
  init:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          sudo apt update
          sudo apt install -y golange make
