# This is a basic workflow to help you get started with Actions

name: Docker Image Publish

# Controls when the action will run. 
on:
  push:
    branches: [main]
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
     
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        shell: bash
        run: |
          sudo apt update
          sudo apt install make
          
      - name: install go
        uses: actions/setup-go@v2.1.3
        with:
             go-version: 1.15
      
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: test controller
        shell: bash
        run: |
          make test
   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Github Registry Login
        uses: docker/login-action@v1.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Github Registry Login
        uses: docker/login-action@v1.6.0
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v2.2.0
        with:
          tags: |
            ghcr.io/${{ github.repository_owner }}/hetzner-operator:latest
            ${{ github.repository_owner }}/hetzner-operator:latest
          push: true

